### ISSUE TITLE
Bug: AI bugs

### ISSUE THREAD

**Issue by nandinhomsf** [Grupinix/Xadrez#89]
# 1-King capturing the pawn while in check instead of capturing the queen

![Imagem do WhatsApp de 2023-05-27 à(s) 11 12 50](https://github.com/Grupinix/Xadrez/assets/78365631/64ce186a-62d1-4790-9595-278a8df58a9a)
#
![image](https://github.com/Grupinix/Xadrez/assets/78365631/43f460c1-65f3-4488-ba87-62d3e4a93cf8)
#
![image](https://github.com/Grupinix/Xadrez/assets/78365631/6d2fb2d3-60f4-4aaa-b454-ef9acb38f409)
#
![image](https://github.com/Grupinix/Xadrez/assets/78365631/21981944-af17-48a7-a664-b4decbc38f17)

# 2-When the king is in a check position, it does not reposition itself to a position that leaves the check and ends the game.
-As the history of the piece takes the previous and current location, when the king is in check at the beginning of the turn without it having moved, it enters an infinite loop in the same place, showing that the king is in check.
-When this bug happens, the AI does not present a request to the server and the game becomes unplayable.

**Comment by felipemsalles** [comment]
-As the history of the piece takes the previous and current location, when the king is in check at the beginning of the turn without it having moved, it enters an infinite loop in the same place, showing that the king is in check.
-When this bug happens, the AI does not present a request to the server and the game becomes unplayable.
